### ISSUE TITLE
An error occurred using the latest version,

### ISSUE THREAD

**Issue by WREQI** [donalffons/opencascade.js#45] opened 2021-05-25 15:17 UTC
I installed and configured according to the document https://github.com/donalffons/opencascade.js/tree/master/doc#using-pre-built-modules, but received the following error. What could be the reason?

![image](https://user-images.githubusercontent.com/35467304/119522565-aa0efc00-bdae-11eb-8509-d7b6f7216bb2.png)

**Comment by donalffons** [comment] 2021-05-25 16:02
Hmm, that probably means that you don't have the latest version of the `opencascade.js@beta` package installed (I accidentally published one or more broken versions some time ago).

If you open up the file `./node_modules/opencascade.js/package.json` in your local project, it should say `"version": "2.0.0-beta.bf4d306"` in line 3. I assume that it has a different version there. To fix this, you need to:

1. run `yarn remove opencascade.js` (or npm)
2. delete your `node_modules` folder
3. delete your `package-lock.json` file (if you're using npm) or your `yarn.lock` file (if you're using yarn)
4. run `yarn add opencascade.js@beta`

It seems that the problem is that the beta builds are not versioned semantically, which gets yarn/npm confused. If you're using the examples, try to `git pull` that project as I pushed a fix for that issue today.

**Comment by donalffons** [comment] 2021-05-25 16:05
...also: You have to do these steps every time you want to update the `opencascade.js@beta` version.

I will hopefully be able to publish a 2.0 version soon - that problem should go away then.

**Closed** 2021-05-25 17:07 UTC
